name: Notion NLP
'on':
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run main.py
        env:
          NOTION_TOKEN: '${{ secrets.NOTION_TOKEN }}'
          NOTION_DATABASE_ID: '${{ secrets.NOTION_DATABASE_ID }}'
          EAI_USERNAME: '${{ secrets.EAI_USERNAME }}'
          EAI_PASSWORD: '${{ secrets.EAI_PASSWORD }}'
        run: python main.py --latest
